### ISSUE TITLE
docs: integrate frame.js debugger

### ISSUE THREAD

**Issue by depatchedmode** [depatchedmode/simplest-frame#22]
todo:
- [x] update docs to link to frame debugger: https://debugger.framesjs.org/debug
- [x] run frames.js starter repo locally alongside `simplest-frame` and see if local debugging works

https://framesjs.org/

**Comment by depatchedmode** [comment]
Works locally! All you have to do is:
1. Clone down the `framejs-starter` repo
2. `yarn install` then `yarn dev`
3. Start your `simplest-frame` repo with `netlify dev` (or `npm/yarn dev`)
3. Go to `http://localhost:3000/debug?http://localhost:3000/debug?url=http://localhost:8888/

<img width="676" alt="image" src="https://github.com/depatchedmode/simplest-frame/assets/84613835/4a05f816-3fa0-4a0f-8f1c-401a11e9a305">

**Comment by jetlej** [comment]
@depatchedmode FYI looks like the URL in your last response here has an extra URL in it
